server:
  port: 8888

spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  server:
    #检测心跳超时保护机制
    enable-self-preservation: false
  instance:
    prefer-ip-address: true